### ISSUE TITLE
Standard configuration not logging click events

### ISSUE THREAD

**Issue by WayneNani** [gopalmallya/plogger#1]
After a fresh install, the config table contains all the default values (including the "click" event for logging). But when enabling the plugin in an application, it does not log click events. Only submit events show up in the PLOGGER table.
Changing the sync interval does not fix this behavior.

**Comment by gopalmallya** [comment]
Hi WayneNani
Thank you for checking out plogger plugin. I tried a fresh install of plogger plugin as follows
1. Installed customer tracker application in APEX 19.2 version from productivity apps (installed Application_id is **356**)
2. git cloned the plogger git clone https://github.com/gopalmallya/plogger.git
3. from SQL developer connected to APEX parsing schema and executed ploggerTable.sql
4. verified plogger table creation by select * from plogger; (empty table) and select * from plogger_config; (default for application ID 107)
5. Updated the plogger_config to change app_id from 107 to 356. update plogger_config set app_id=356 where app_id=107
6. on Page Zero of customer tracker (app id 356) added dynamic action on Page Load and set true action to plogger plugin
7. opened customer tracker application and clicked on couple buttons.
8. veriified click events are logger in plogger table . select * from plogger; see the records below.
APP_ID	PAGE_ID	SESSION_ID	EVENT_ID	EVENT_TYPE	EVENT_NAME	EVENT_TIME_STAMP	EVENT_TARGET_HTML
356	59	5560854663521	2021-12-13T16:30:01.650Z	event	click	5700.100000023842	<span class="t-Icon fa fa-tiles-2x2" title="Logo View"></span>
356	59	5560854663521	2021-12-13T16:30:01.682Z	event	click	5700.100000023842	<input type="radio" id="P59_DISPLAY_AS_1" name="P59_DISPLAY_AS" value="LOGOS">
356	59	5560854663521	2021-12-13T16:30:04.627Z	event	click	8646.300000071526	<input type="radio" id="P59_DISPLAY_AS_2" name="P59_DISPLAY_AS" value="REPORT">
356	59	5560854663521	2021-12-13T16:30:04.595Z	event	click	8646.300000071526	<label for="P59_DISPLAY_AS_2"><span class="t-Icon fa fa-table" title="Report View"></span><span class="u-VisuallyHidden">Report View</span></label>

Few things to verify for you
1. Please check the app_id in plogger_config and make sure it has your application ID for which your are testing the plugin, by updating the app_id. update plogger_config set app_id=<Your app ID> where app_id=107; or delete all records from plogger_config and insert records with your app_id.
2. Please check if dynamic action is created on page zero on page load event.
3. I tested on google chrome, so even after above update, if click events are not being logger, try using chrome browser and let me know.

Thanks again for trying this plug-in.

Gopal

**Comment by WayneNani** [comment]
Hey Gopal,

thanks for getting back to me. You are absolutely right, I just forgot to change the APP_ID in the config table. Now it works!
Just a quick follow up, before I close this issue: Is it intended that the click event is triggered multiple times? I get 4 entries for a single click, each one around 10 ms after the one before. They are exactly the same except for the EVENT_ID.

Thanks for the super useful plugin!

Jakob

**Comment by gopalmallya** [comment]
Hello
I tested the clicks, and most of the time, plogger only logged one click event, but sometimes, it did log 3 events for same button click, with different event timestamp (event ID). I believe this has to do with underlying theme and js used by APEX. plogger just logs any click event thrown by browser and the fact that event ID is different with different timestamp , means these are separate click events. There is no way for me to fix this issue, because I cannot differentiate between events occurring for same button at different times. I guess the solution is to write select on plogger to select only relevant clicks within an interval say 100ms using max function for analyses of click event on page.  Also check this out https://community.oracle.com/tech/developers/discussion/3720150/apex-5-0-onclick-event-firing-twice

**Comment by WayneNani** [comment]
Okay, this is great to know. Thanks for the quick response and have a great day!
